/**
 * 卓球用語辞典 - 拡張版
 * 127個の用語を5つのカテゴリに分類
 */

export interface GlossaryTerm {
  id: string;
  name: string;
  category: 'rules' | 'equipment' | 'techniques' | 'tactics' | 'other';
  description: string;
  relatedTerms?: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export const glossaryTerms: GlossaryTerm[] = [
  // ルール編（25個）
  {
    id: 'rule-001',
    name: 'ラリー',
    category: 'rules',
    description: '選手同士がボールを打ち合うこと。試合の基本的な流れを指します。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-002',
    name: 'サーブ・サーバー',
    category: 'rules',
    description: '最初にボールを打つ行為のこと。サーブを打つ選手をサーバーといいます。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-003',
    name: 'レシーブ・レシーバー',
    category: 'rules',
    description: '相手のサーブを返球すること。レシーブをする選手をレシーバーといいます。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-004',
    name: 'ゲーム',
    category: 'rules',
    description: '11点先取の試合のこと。通常、このゲームを数回行って、3回や5回勝利した方が試合全体の勝利者となります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-005',
    name: 'マッチ',
    category: 'rules',
    description: '1試合のこと。通常、3ゲーム先取や5ゲーム先取で勝敗が決まります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-006',
    name: 'デュース',
    category: 'rules',
    description: 'ポイントが10対10の同点状態のこと。2点差がつくまで、試合は継続されます。10対10以降はサーブは一本交代となります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-007',
    name: 'カウント',
    category: 'rules',
    description: '現時点での互いの得点を示すもので、主に審判がコールをします。サーブする側の点数を先にコールするのが通常です。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-008',
    name: 'チェンジコート・チェンジエンド',
    category: 'rules',
    description: '各ゲーム終了後に、選手がコートの位置を交換すること。公式試合ではチェンジエンドと呼ばれることが多いです。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-009',
    name: 'ネットイン',
    category: 'rules',
    description: '打ったボールがネットにかかり、相手コートに入ったこと。軌道が変化するため、ラリー終了後に軽く謝罪をするマナーがあります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-010',
    name: 'レット',
    category: 'rules',
    description: 'サーブ時にネットインをした場合、サーブがやり直しになる事。ネットにかかっても自分のコートにボールが落ちた場合は、サーブミスで失点です。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-011',
    name: 'フォルト',
    category: 'rules',
    description: 'サーブのルールに違反した時に、失点となる事。例えば、トスの高さが低いことやボールが見えないなどがよくあります。',
    difficulty: 'intermediate',
  },
  {
    id: 'rule-012',
    name: 'サポートイン',
    category: 'rules',
    description: 'ボールがネットの支柱に当たって、相手コートに入ること。サーブ時にはやり直しとなるが、ラリー中は有効となります。',
    difficulty: 'advanced',
  },
  {
    id: 'rule-013',
    name: 'オブストラクション',
    category: 'rules',
    description: '相手のボールが自分のコートにバウンドする前に、ラケット等で触れてしまう事。身体にあたってもダメなので注意が必要です。',
    difficulty: 'advanced',
  },
  {
    id: 'rule-014',
    name: 'インプレー',
    category: 'rules',
    description: 'プレー中のこと。サーブの際にボールを手のひらに静止させた状態から、ラリーが終わるまでのことを指します。',
    difficulty: 'intermediate',
  },
  {
    id: 'rule-015',
    name: 'シングルス',
    category: 'rules',
    description: '選手と選手が一対一で行う試合形式のこと。漢字一文字で「単」と表現されることがあります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-016',
    name: 'ダブルス',
    category: 'rules',
    description: '二人の選手がペアになって、二対二で行う試合形式のこと。漢字一文字で「複」と表現されることがあります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-017',
    name: 'サイド',
    category: 'rules',
    description: '卓球台の側面部分のこと。ここに当たった場合は無効となり、失点となります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-018',
    name: 'エッジ・エッジボール',
    category: 'rules',
    description: '卓球台の角部分のこと。ここに当たった場合は有効となり、ラリーやサーブは継続となります。ネットイン同様に当たった場合は謝罪のマナーがあります。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-019',
    name: 'オープンハンドサービス',
    category: 'rules',
    description: 'ルールに基づいた正式なサーブの打ち方で、手のひらを開いてボールを16㎝以上垂直に投げ上げます。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-020',
    name: 'サーバーズ・ライト・ハーフコート',
    category: 'rules',
    description: 'ダブルス形式の場合、サーブを打つ際に使用される右半分のコート領域のことです。サーバーからレシーバーへ対角線上にサーブを打たなければいけません。',
    difficulty: 'advanced',
  },
  {
    id: 'rule-021',
    name: 'バッドマナー',
    category: 'rules',
    description: '遅延行為、暴言など競技マナーに反する全ての行為のことを指し、警告や失点の対象となります。',
    difficulty: 'intermediate',
  },
  {
    id: 'rule-022',
    name: 'タイムアウト',
    category: 'rules',
    description: '1試合に1回、1分以内で認められる作戦会議や休憩のための試合中断のこと。オープン戦や学生の地方大会等では、認められてないことがほとんどです。',
    difficulty: 'intermediate',
  },
  {
    id: 'rule-023',
    name: 'タオル休憩',
    category: 'rules',
    description: '両者の得点合計が6の倍数になった時にのみ、タオルを使って汗を拭くなどの短時間の休憩タイムが認められます。',
    difficulty: 'beginner',
  },
  {
    id: 'rule-024',
    name: '促進ルール',
    category: 'rules',
    description: '1ゲーム10分経過で両者合計18点未満の場合に適用される試合時間短縮ルールで、サーブ側は13回以内に得点する必要があります。',
    difficulty: 'advanced',
  },
  {
    id: 'rule-025',
    name: 'オンライン',
    category: 'rules',
    description: 'ダブルスでサーブがセンターライン上にバウンドした状態で、ボールの一部でも線に触れていれば有効となること。',
    difficulty: 'intermediate',
  },

  // 道具・卓球台編（28個）
  {
    id: 'equip-001',
    name: 'ボール',
    category: 'equipment',
    description: '卓球に使用する白い球のこと。公式戦等では使用されるボールにも規格があります。潰れたとしても熱湯をかければ、中の空気が膨張して元に戻ることもあります。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-002',
    name: 'コート',
    category: 'equipment',
    description: '競技者がプレーを行う卓球台の表面全体のことで、エッジや台の角部分も含まれます。大会などでは「何番コートで試合です」と呼ばれることが多いですね。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-003',
    name: 'ネット',
    category: 'equipment',
    description: '卓球台の中央部分を二分割する高さ15.25cmの網状の仕切りのことで、台に対して垂直に設置されています。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-004',
    name: 'サポート',
    category: 'equipment',
    description: 'ネットを卓球台に固定するための支柱や器具で、ネットの一部として扱われるものです。間違ってサポーターと呼ぶこともあります。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-005',
    name: '自陣',
    category: 'equipment',
    description: '自分側の卓球台の半分の領域のことで、ネットによって相手陣と区分されます。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-006',
    name: 'センターライン',
    category: 'equipment',
    description: '卓球台の中央にネットと垂直に引かれた白い線で、主にダブルス競技でサーブエリアを区分するために使用されるラインです。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-007',
    name: 'サイドライン',
    category: 'equipment',
    description: '卓球台の両端にネットに対して垂直に引かれた白い境界線になります。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-008',
    name: 'エンドライン',
    category: 'equipment',
    description: '卓球台の端部にネットと平行に引かれた白い境界線のことです。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-009',
    name: 'フォア',
    category: 'equipment',
    description: 'プレイヤーの利き腕側のコート領域を表し、右利きの場合は右側の範囲です。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-010',
    name: 'バック',
    category: 'equipment',
    description: 'プレイヤーの利き腕と反対側のコート領域のこと。右利きの場合は左側の範囲となり、「バック側」と表現されることが多いです。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-011',
    name: 'ミドル',
    category: 'equipment',
    description: 'プレイヤーの身体正面付近のコース領域のことで、フォアハンドとバックハンドのどちらで打球するか判断が困難な位置です。最も打球が難しいコースとされています。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-012',
    name: 'ラケット',
    category: 'equipment',
    description: 'ボールを打球するために使用する木製の道具を指し、必ずラバーを貼り付けて使用します。木の板だけでなく、ラバーを貼った状態も含めてラケットと呼ぶことが多いです。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-013',
    name: 'シェークハンド',
    category: 'equipment',
    description: '握手をするような形でラケットを握る持ち方のことで、両面にラバーを貼って使用する最も一般的なスタイルです。フォアハンドとバックハンドの切り替えがしやすいのが特徴になります。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-014',
    name: 'ペンホルダー',
    category: 'equipment',
    description: 'ペンを持つような形でラケットを握る持ち方を表し、日本式と中国式の二種類があります。手首の可動域が広く、台上のプレーやサーブが得意なラケットです。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-015',
    name: '日本式ペンホルダー',
    category: 'equipment',
    description: 'フォア面のみにラバーを貼るペンホルダーグリップのラケットのことです。フォアハンド主体のプレースタイルに適しています。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-016',
    name: '中国式ペンホルダー',
    category: 'equipment',
    description: 'ペンホルダーグリップでありながら両面にラバーを貼ることができる丸型のラケットを指します。バックハンドも使用可能で、中国人選手がよく使用しています。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-017',
    name: 'グリップ',
    category: 'equipment',
    description: 'ラケットの握り部分のことで、またはラケットの持ち方そのものを指します。シェークハンドには複数の形状が存在します。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-018',
    name: 'ブレード',
    category: 'equipment',
    description: 'ラケットの打球面部分を表し、ラバーを貼り付ける箇所のことです。木材の枚数や素材によって特性が変わります。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-019',
    name: '木材ラケット',
    category: 'equipment',
    description: 'ブレード部分がすべて木材で構成されたラケットのことで、初級者から上級者まで幅広く使用されています。特殊素材ラケット以外はほとんどが木材ラケットになります。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-020',
    name: '合板ラケット',
    category: 'equipment',
    description: '複数の木材板を重ね合わせて製作されたラケットを指し、枚数により特性が異なります。基本的には枚数が多いほど反発力が高くなるのが特徴です。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-021',
    name: '特殊素材ラケット',
    category: 'equipment',
    description: '木材以外にカーボンやグラスファイバーなどの素材を組み込んだラケットのことです。高い反発力を持ち、特にカーボン入りは上級者向けとなるでしょう。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-022',
    name: 'ラバー',
    category: 'equipment',
    description: 'ラケットに貼り付ける赤または黒色のゴム製品を表し、シートとスポンジの二層構造になっています。ラバーの種類によって打球感が大きく変わるので、慎重に選びましょう。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-023',
    name: '裏ソフト',
    category: 'equipment',
    description: '表面がツルツルとしたラバーのことで、強い回転とスピードを生み出すことができる最も一般的なタイプです。「裏ソフトラバー」とも呼ばれています。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-024',
    name: '表ソフト',
    category: 'equipment',
    description: '表面に小さな粒が配列されたラバーのことです。相手の回転の影響を受けにくい特性があり、「表ソフトラバー」とも呼ばれます。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-025',
    name: '粒高',
    category: 'equipment',
    description: '表面の粒が細く長いラバーのことで、相手の回転を打ち消し独特な変化球を生み出すことが可能です。「イボ高」とも呼ばれます。',
    difficulty: 'beginner',
  },
  {
    id: 'equip-026',
    name: '粘着',
    category: 'equipment',
    description: '裏ソフトラバーの一種で表面の粘着性を極限まで高めたもので、強力な回転をかけることが可能です。中国人選手に使用者が多いです。',
    difficulty: 'intermediate',
  },
  {
    id: 'equip-027',
    name: 'アンチラバー',
    category: 'equipment',
    description: '表面がツルツルでボールがスリップする裏ラバーの一種のことで、回転をかけることができず相手の回転を残した返球となります。かなり特殊なラバーで使用選手は減少しています。',
    difficulty: 'advanced',
  },
  {
    id: 'equip-028',
    name: '異質ラバー',
    category: 'equipment',
    description: '一般的な裏ソフト以外のラバーの総称を指し、表ソフト、粒高、アンチラバーなどが含まれます。裏ラバーが主流なので、それ以外をまとめて異質と呼びます。',
    difficulty: 'intermediate',
  },

  // 技術編（40個）
  {
    id: 'tech-001',
    name: 'ニュートラル',
    category: 'techniques',
    description: 'あらゆるボールにすぐに対応できる基本的な構えや位置を表し、どのプレーでも最初の状態のことを指します。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-002',
    name: 'スイング',
    category: 'techniques',
    description: '腕やラケットを振る動作全般のことです。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-003',
    name: 'バックスイング',
    category: 'techniques',
    description: '打球に勢いをつけるため腕を後方に引く準備動作を指し、テイクバックとも呼ばれることが多いです。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-004',
    name: 'インパクト',
    category: 'techniques',
    description: 'ボールがラケットに接触する瞬間のことです。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-005',
    name: 'ミート',
    category: 'techniques',
    description: 'ボールがラケットに当たる際の力加減や強さを表し、強くミートすれば打球の威力が上がり、弱くミートすればスピード等は落ちます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-006',
    name: 'フォロースルー',
    category: 'techniques',
    description: 'インパクト後の腕の振り抜きや継続動作のことです。フォロースルーの終わりは「フィニッシュ」と言います。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-007',
    name: '打球感',
    category: 'techniques',
    description: 'ボールをインパクトした際に感じる手応えや感触を指し、「打球感が硬い」などと表現することがあります。主にラバーやラケットを買い替えた時などに用います。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-008',
    name: '球離れ',
    category: 'techniques',
    description: 'ラケットにボールが接触してから離れるまでの時間的感覚のことで、「球持ち」とも言います。',
    difficulty: 'advanced',
  },
  {
    id: 'tech-009',
    name: '弾道',
    category: 'techniques',
    description: '打球されたボールの飛行軌道を意味します。山なりのボールは弾道が高いといいます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-010',
    name: 'フットワーク',
    category: 'techniques',
    description: 'プレー中の足の動きや足さばき技術のことで、卓球において極めて重要な要素です。動いて打つときの動作の一つになります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-011',
    name: 'スピン・回転',
    category: 'techniques',
    description: 'ボールにかかる回転全般のことです。上回転、下回転、横回転などがあります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-012',
    name: '上回転',
    category: 'techniques',
    description: 'ボールの進行方向と同じ向きの回転を表し、ドライブ回転やトップスピンとも呼ばれます。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-013',
    name: '順横回転',
    category: 'techniques',
    description: '時計回りの横回転のことです。右利きの場合にボールが右方向に変化し、逆横回転と区別して使われます。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-014',
    name: '逆横回転',
    category: 'techniques',
    description: '反時計回りの横回転を指し、右利きの場合にボールが左方向に変化していきます。巻き込みサーブやYGサーブがこの回転になります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-015',
    name: '下回転',
    category: 'techniques',
    description: 'ボールの進行方向と逆向きの回転のことで、カットやバックスピンとも呼ばれます。この回転のボールをラケットに当てると、下に落ちていきます。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-016',
    name: 'ナックル',
    category: 'techniques',
    description: '回転のかかっていない無回転状態のボールのことです。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-017',
    name: 'ぶつ切り',
    category: 'techniques',
    description: 'サーブにおいて強力な回転がかかっていることや、強力な下回転がかかってるカットのことを意味します。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-018',
    name: 'トス',
    category: 'techniques',
    description: 'サーブを打つ前にボールを上方に投げ上げる動作を指し、16cm以上垂直に投げ上げる必要があります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-019',
    name: 'フォアサーブ',
    category: 'techniques',
    description: 'フォアハンドで行うサーブのことで、現代卓球における主流のサーブ技術です。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-020',
    name: 'バックサーブ',
    category: 'techniques',
    description: 'バックハンドで行うサーブを表します。主にカットマンや戦術変更時に使用され、可動域が限られるため、フォアサーブよりは使用頻度が少ないです。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-021',
    name: 'ショートサーブ',
    category: 'techniques',
    description: '相手コートで2バウンド以上する短いサーブのことで、相手の強打を封じる効果があります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-022',
    name: 'ロングサーブ',
    category: 'techniques',
    description: '相手コートの奥深くまで届く長いサーブを指し、スピードを活かして得点を狙えます。相手に強打されるリスクもあるので、注意が必要です。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-023',
    name: 'YGサーブ',
    category: 'techniques',
    description: '独特なフォームで逆横回転をかけるフォアサーブのことで、ヤング・ジェネレーションの略称です。「YG」や「ヤンジェネ」とも呼ばれています。',
    difficulty: 'advanced',
  },
  {
    id: 'tech-024',
    name: '巻き込みサーブ',
    category: 'techniques',
    description: '手首を内側に巻き込むようにして逆横回転をかけるサーブ技術を表し、フェイクモーションを加えやすいのが特徴です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-025',
    name: 'しゃがみ込みサーブ',
    category: 'techniques',
    description: 'しゃがみながら打つことでボールの落下速度を利用し、強い回転をかけるサーブのことです。通常のサーブよりも強い回転をかけられます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-026',
    name: '王子サーブ',
    category: 'techniques',
    description: 'しゃがみ込みサーブの一種を指し、大阪の王子町で考案されたバック面でのサイドスピンサーブです。顔の前でラケットを右上から左下方向に振るのが特徴です。',
    difficulty: 'advanced',
  },
  {
    id: 'tech-027',
    name: 'フェイント',
    category: 'techniques',
    description: '相手にコースを読ませないよう手や体、顔の向きを使って惑わせる技術のことです。フェイクモーションとも呼ばれます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-028',
    name: 'ツッツキ',
    category: 'techniques',
    description: '主に台上で下回転をかけて返球する基本的な守備技術のことです。相手のツッツキを攻撃するのは「ツッツキ打ち」と言います。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-029',
    name: 'フリック',
    category: 'techniques',
    description: '台上の短いボールを払うようにして弾き打つ攻撃的技術を指し、「はらい」「はらって打つ」とも言うでしょう。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-030',
    name: 'チキータ',
    category: 'techniques',
    description: '手首を活用したバックハンドで横回転をかけて返球する現代卓球の主流レシーブ技術のことです。チキータバナナのように曲がることから名付けられました。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-031',
    name: 'ストップ',
    category: 'techniques',
    description: '相手コートで2バウンド以上するようボールの勢いを殺してネット際に落とすレシーブ方法で、ボールの回転やスピードをうまく殺すのが特徴です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-032',
    name: '流し',
    category: 'techniques',
    description: 'ラケットを横にスライドさせて横回転をかけ、左右に打ち分ける台上技術のことです。',
    difficulty: 'advanced',
  },
  {
    id: 'tech-033',
    name: 'フォアハンド',
    category: 'techniques',
    description: '利き腕側でボールを打つことを指し、シェークハンドでは手のひら側での打球を意味します。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-034',
    name: 'バックハンド',
    category: 'techniques',
    description: '利き腕と反対側でボールを打つ技術のことで、シェークハンドでは手の甲側での打球です。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-035',
    name: 'スマッシュ',
    category: 'techniques',
    description: 'ボールを叩くようにして打つ強打を表し、直線的な軌道で決定打となりやすいのが特徴です。「パカン！」と乾いた音がなります。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-036',
    name: 'ドライブ',
    category: 'techniques',
    description: '上回転をかけて弧線を描く軌道で返球する攻撃のこと。ドライブ主戦型の選手が多用する技術です。強力な上回転がかかっているので、ブロックが甘いとボールが飛んでいってしまいます。',
    difficulty: 'beginner',
  },
  {
    id: 'tech-037',
    name: 'ループドライブ',
    category: 'techniques',
    description: '強い回転をかけて山なりの軌道で返球するドライブの一種を指し、強い下回転のボールに対してよく使用されます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-038',
    name: 'カーブドライブ',
    category: 'techniques',
    description: '左回転を加えたドライブのことで、バウンド後に左方向へ大きく曲がります。左利きの選手では右に曲がります。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-039',
    name: 'シュートドライブ',
    category: 'techniques',
    description: '右回転を加えたドライブを表し、バウンド後に右方向へ大きく曲がります。左利きの選手では左に曲がります。',
    difficulty: 'intermediate',
  },
  {
    id: 'tech-040',
    name: 'スピードドライブ',
    category: 'techniques',
    description: '回転よりもスピードを重視したドライブのことで、相手が反応しづらいコースに打ちぬくように打ちます。',
    difficulty: 'intermediate',
  },

  // 戦術・戦型編（20個）
  {
    id: 'tactic-001',
    name: '前陣',
    category: 'tactics',
    description: '卓球台から1メートル以内の近距離領域のことです。',
    difficulty: 'beginner',
  },
  {
    id: 'tactic-002',
    name: '中陣',
    category: 'tactics',
    description: '卓球台から1～2メートル離れた中距離に位置することを意味します。',
    difficulty: 'beginner',
  },
  {
    id: 'tactic-003',
    name: '後陣',
    category: 'tactics',
    description: '卓球台から2メートル以上離れた遠距離位置のことで、主にカットマンがプレーする位置になります。',
    difficulty: 'beginner',
  },
  {
    id: 'tactic-004',
    name: 'ドライブ型',
    category: 'tactics',
    description: 'ドライブを多用して攻撃的に戦う最も一般的なプレースタイルを指し、裏ラバーを使用します。攻撃を主体とするプレースタイルです。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-005',
    name: '前陣速攻型',
    category: 'tactics',
    description: 'テンポの速さとスピードで勝負を決める前陣でのプレースタイルのことで、特に女子選手や表ソフトラバーの使用者に多い戦型です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-006',
    name: '異質速攻型',
    category: 'tactics',
    description: 'フォア面とバック面で異なるラバーを使用する前陣速攻型のプレースタイルになり、裏ラバーと表ラバーの組み合わせが主流です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-007',
    name: 'カットマン',
    category: 'tactics',
    description: '後陣で相手のボールをカットで返球し、守備的に戦うプレースタイルの選手を指します。粘り強くラリーをし、相手の甘いボールを狙って攻撃していきます。',
    difficulty: 'beginner',
  },
  {
    id: 'tactic-008',
    name: 'ブロック型',
    category: 'tactics',
    description: '相手の攻撃をブロックで凌ぎながら戦う守備的なプレースタイルのことです。主に前陣で相手の攻撃を返球します。横回転を加えたブロックや、相手を動かすブロックや、カウンタードライブなどで相手を翻弄していくプレースタイルです。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-009',
    name: 'カウンター',
    category: 'tactics',
    description: '相手の強打の威力を利用して早い打点で反撃することです。相手のドライブを同じくドライブで返すことをカウンターということが多いです。',
    difficulty: 'advanced',
  },
  {
    id: 'tactic-010',
    name: 'カウンタードライブ',
    category: 'tactics',
    description: '相手のドライブに対してドライブで攻撃し返す技術のことで、相手の威力を利用してより強いボールを返球することです。',
    difficulty: 'advanced',
  },
  {
    id: 'tactic-011',
    name: '角度打ち',
    category: 'tactics',
    description: 'ラケットの角度を調整してボールを弾き返す技術を表します。弱い下回転などを素早く打ちぬけるので、覚えれば便利な打球です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-012',
    name: 'ショート',
    category: 'tactics',
    description: 'ペンホルダーでのバックハンドの基本技術のことで、ラケット角度でボールを合わせる守備的な技術です。主にペンのバックハンドで使われる用語になります。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-013',
    name: 'ハーフボレー',
    category: 'tactics',
    description: 'バウンド直後を捉えて打つバックハンド技術を指し、ショートより攻撃的です。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-014',
    name: 'プッシュ',
    category: 'tactics',
    description: '粒高ペンホルダーのバックハンドで腕を突き出すようにボールを弾く攻撃的技術のことです。バウンド直後のボールに対して使用します。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-015',
    name: '裏面打法',
    category: 'tactics',
    description: '中国式ペンホルダーで裏面のラバーを使用するバックハンド打法を意味します。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-016',
    name: 'カット',
    category: 'tactics',
    description: '台から離れた位置でボールに下回転をかけて返球する守備技術のことです。ラケットを上から下に大きくスイングします。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-017',
    name: 'カットブロック',
    category: 'tactics',
    description: '強打されたボールのバウンド直後を捉えて下回転をかけながらブロックする高等テクニックを指します。',
    difficulty: 'advanced',
  },
  {
    id: 'tactic-018',
    name: '引き合い',
    category: 'tactics',
    description: '台から離れた場所で互いにドライブを打ち合う展開のことです。卓球の見どころの一つといえます。',
    difficulty: 'intermediate',
  },
  {
    id: 'tactic-019',
    name: '三球目攻撃',
    category: 'tactics',
    description: '自分のサーブに対する相手のレシーブを攻撃的に打つ基本戦術を指し、サーブを1球目とカウントした時の3球目という意味です。サーブから三球目攻撃がどれだけ強力かで試合の勝敗は大きく左右されます。',
    difficulty: 'beginner',
  },
  {
    id: 'tactic-020',
    name: '四球目攻撃',
    category: 'tactics',
    description: '自分のレシーブ後の相手の返球を狙い打つ戦術のことです。3球目攻撃と同様に数えると4球目に当たります。',
    difficulty: 'intermediate',
  },

  // その他（14個）
  {
    id: 'other-001',
    name: '回り込み',
    category: 'other',
    description: 'バック側に来たボールを回り込んでフォアハンドで打つ動作や技術を表し、バックハンドで打つのではなく、フォアハンドで処理します。',
    difficulty: 'beginner',
  },
  {
    id: 'other-002',
    name: '飛びつき',
    category: 'other',
    description: 'フォア側への打球に対してバック側から大きく動いて打つ動作のことです。回り込んだ後によく見られる動きになります。',
    difficulty: 'intermediate',
  },
  {
    id: 'other-003',
    name: '乱打',
    category: 'other',
    description: '連続的にボールを打ち合う練習方法を指します。大会が始まる前に全選手がそれぞれ台でウォーミングアップすることを意味することもあります。',
    difficulty: 'beginner',
  },
  {
    id: 'other-004',
    name: '多球練習',
    category: 'other',
    description: '複数のボールを使用して効率的に技術を習得する練習方法のことです。短時間で多くの打球練習ができます。大量のボールを用意し、片方がボールを連続で出し、練習側がそれを連続で打ち返していくやり方です。',
    difficulty: 'beginner',
  },
  {
    id: 'other-005',
    name: 'マシン',
    category: 'other',
    description: '自動的にボールを送球する練習器具を表し、一人でも効率的に練習できます。回転、コース、スピード、パターンを指定できるため、一人で多球練習をすることが可能です。',
    difficulty: 'intermediate',
  },
  {
    id: 'other-006',
    name: 'スリースター',
    category: 'other',
    description: '最高品質を示すボールの等級表示のことで、公式試合で使用されます。★が3つ付いているボールです。',
    difficulty: 'beginner',
  },
  {
    id: 'other-007',
    name: 'スペア',
    category: 'other',
    description: 'スペアラケットのことを意味します。万が一、メインのラケットが試合中に壊れた場合のために用意しておきます。',
    difficulty: 'intermediate',
  },
  {
    id: 'other-008',
    name: 'フィッシュ',
    category: 'other',
    description: '台から離れた場所から相手コートに低く返球し、上回転でボールを伸ばして相手のミスを誘う技術を表します。高くボールをあげて凌ぐロビングと間違えないようにしましょう。',
    difficulty: 'advanced',
  },
  {
    id: 'other-009',
    name: '逆モーション',
    category: 'other',
    description: '相手の予測とは異なる動作でボールを打つフェイント技術のことです。サーブを打球した後に行うスイングも含まれます。',
    difficulty: 'advanced',
  },
  {
    id: 'other-010',
    name: 'レシーブ',
    category: 'other',
    description: 'サーブを打ち返すことです。',
    difficulty: 'beginner',
  },
  {
    id: 'other-011',
    name: 'サービス・サーブ',
    category: 'other',
    description: 'ラリー開始時に最初に打つボールを指し、正式にはサービスと呼ばれます。これからラリーが始まります。',
    difficulty: 'beginner',
  },
  {
    id: 'other-012',
    name: 'ブロック',
    category: 'other',
    description: 'ラケットをあまり動かさず前陣で、相手の攻撃を返球する守備的技術のこと。卓球においても相手の攻撃を台の近くで止めることです。',
    difficulty: 'intermediate',
  },
  {
    id: 'other-013',
    name: 'ロビング',
    category: 'other',
    description: '台から離れた後陣で、高くボールを上げて返球する守備技術のことです。',
    difficulty: 'intermediate',
  },
  {
    id: 'other-014',
    name: '逆チキータ',
    category: 'other',
    description: 'チキータとは反対の回転を加えるレシーブ技術のことです。より高度なテクニックとされています。',
    difficulty: 'advanced',
  },
];

export function getGlossaryByCategory(category: GlossaryTerm['category']): GlossaryTerm[] {
  return glossaryTerms.filter((term) => term.category === category);
}

export function getGlossaryByDifficulty(difficulty: GlossaryTerm['difficulty']): GlossaryTerm[] {
  return glossaryTerms.filter((term) => term.difficulty === difficulty);
}

export function searchGlossary(query: string): GlossaryTerm[] {
  const lowerQuery = query.toLowerCase();
  return glossaryTerms.filter(
    (term) =>
      term.name.toLowerCase().includes(lowerQuery) ||
      term.description.toLowerCase().includes(lowerQuery),
  );
}

export const glossaryCategories = [
  { id: 'rules', name: 'ルール編', count: 25, color: '#FFE5E5' },
  { id: 'equipment', name: '道具・卓球台編', count: 28, color: '#E5F0FF' },
  { id: 'techniques', name: '技術編', count: 40, color: '#E5FFE5' },
  { id: 'tactics', name: '戦術・戦型編', count: 20, color: '#FFF5E5' },
  { id: 'other', name: 'その他', count: 14, color: '#F5E5FF' },
] as const;
