/**
 * 世界卓球ランキング上位100名のプロ選手データベース
 * 2026年2月3日時点の最新ランキング情報を含む
 */

export interface ProPlayer {
  id: string;
  rank: number;
  name: string;
  nameEnglish: string;
  country: string;
  countryCode: string;
  playingStyle: "シェークハンド" | "ペンホルダー" | "その他";
  specialties: string[];
  description: string;
  achievements?: string[];
  points?: number;
}

export const proPlayersMega: ProPlayer[] = [
  {
    id: "wang-chuqin",
    rank: 1,
    name: "王楚欽",
    nameEnglish: "WANG Chuqin",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "中国の若き才能。強力なフォアドライブと安定したバックハンドが特徴。",
    points: 9925,
  },
  {
    id: "lin-shidong",
    rank: 2,
    name: "林詩棟",
    nameEnglish: "LIN Shidong",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派選手。バランスの取れたプレースタイルで安定した成績を出している。",
    points: 7525,
  },
  {
    id: "hugo-calderano",
    rank: 3,
    name: "ヒューゴ・カルデラノ",
    nameEnglish: "Hugo CALDERANO",
    country: "ブラジル",
    countryCode: "BRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ブラジルの代表選手。強力なフォアハンドとアグレッシブなプレースタイルが特徴。",
    points: 6050,
  },
  {
    id: "truls-moregard",
    rank: 4,
    name: "モーレゴード（トルルス・モアガド）",
    nameEnglish: "Truls MOREGARD",
    country: "スウェーデン",
    countryCode: "SWE",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "スウェーデンの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 5840,
  },
  {
    id: "tomokazu-harimoto",
    rank: 5,
    name: "張本智和",
    nameEnglish: "HARIMOTO Tomokazu",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "日本の若き才能。強力なフォアドライブと高い技術力で国際舞台で活躍。",
    points: 5785,
  },
  {
    id: "felix-lebrun",
    rank: 6,
    name: "フェリックス・ルブラン",
    nameEnglish: "Felix LEBRUN",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "サーブ"],
    description: "フランスの若手選手。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 4260,
  },
  {
    id: "liang-jingkun",
    rank: 7,
    name: "梁靖崑",
    nameEnglish: "LIANG Jingkun",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと安定した守備が特徴。",
    points: 3900,
  },
  {
    id: "sora-matsushima",
    rank: 8,
    name: "松島輝空",
    nameEnglish: "MATSUSHIMA Sora",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "日本の実力派。攻撃的なプレースタイルと高い技術力で知られている。",
    points: 3305,
  },
  {
    id: "lin-yun-ju",
    rank: 9,
    name: "林昀儒",
    nameEnglish: "LIN Yun-Ju",
    country: "台湾",
    countryCode: "TPE",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "台湾の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 3050,
  },
  {
    id: "alexis-lebrun",
    rank: 10,
    name: "アレクシス・ルブラン",
    nameEnglish: "Alexis LEBRUN",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "サーブ"],
    description: "フランスの有望選手。フェリックスの兄。テクニカルなプレースタイルが特徴。",
    points: 2710,
  },
  {
    id: "dang-qiu",
    rank: 11,
    name: "邱党",
    nameEnglish: "Dang QIU",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "ドイツの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 2665,
  },
  {
    id: "xiang-peng",
    rank: 12,
    name: "向鵬",
    nameEnglish: "XIANG Peng",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 2625,
  },
  {
    id: "woojin-jang",
    rank: 13,
    name: "張禹珍",
    nameEnglish: "JANG Woojin",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "韓国の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 2386,
  },
  {
    id: "benedikt-duda",
    rank: 14,
    name: "ベネディクト・デューダ",
    nameEnglish: "Benedikt DUDA",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ドイツの実力派。強力なフォアドライブと安定した守備が特徴。",
    points: 2375,
  },
  {
    id: "darko-jorgic",
    rank: 15,
    name: "ダルコ・ヨルジッチ",
    nameEnglish: "Darko JORGIC",
    country: "スロベニア",
    countryCode: "SLO",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "スロベニアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 2055,
  },
  {
    id: "jaehyun-an",
    rank: 16,
    name: "安宰賢",
    nameEnglish: "AN Jaehyun",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "韓国の実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 1820,
  },
  {
    id: "simon-gauzy",
    rank: 17,
    name: "ゴジ・シモン",
    nameEnglish: "Simon GAUZY",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "フランスの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 1795,
  },
  {
    id: "anders-lind",
    rank: 18,
    name: "アンデシュ・リンド",
    nameEnglish: "Anders LIND",
    country: "デンマーク",
    countryCode: "DEN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "デンマークの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 1790,
  },
  {
    id: "patrick-franziska",
    rank: 19,
    name: "パトリック・フランチスカ",
    nameEnglish: "Patrick FRANZISKA",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ドイツの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 1685,
  },
  {
    id: "shunsuke-togami",
    rank: 20,
    name: "戸上隼輔",
    nameEnglish: "TOGAMI Shunsuke",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "日本の実力派。強力なフォアドライブと高い技術力で国際舞台で活躍。",
    points: 1565,
  },
  {
    id: "kanak-jha",
    rank: 21,
    name: "カナク・ジャー",
    nameEnglish: "Kanak JHA",
    country: "アメリカ",
    countryCode: "USA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "アメリカの有望選手。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 1470,
  },
  {
    id: "junsung-oh",
    rank: 22,
    name: "オ・ジュンソン",
    nameEnglish: "OH Junsung",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "韓国の実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 1450,
  },
  {
    id: "qihao-zhou",
    rank: 23,
    name: "ジョウ・チーハオ",
    nameEnglish: "ZHOU Qihao",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 1410,
  },
  {
    id: "ruibo-wen",
    rank: 24,
    name: "温瑞博",
    nameEnglish: "WEN Ruibo",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "中国の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 1300,
  },
  {
    id: "dimitrij-ovtcharov",
    rank: 25,
    name: "ドミトリ・オフチャロフ",
    nameEnglish: "Dimitrij OVTCHAROV",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ドイツの実力派。強力なフォアドライブと安定した守備が特徴。",
    points: 1280,
  },
  {
    id: "yukiya-uda",
    rank: 26,
    name: "宇田幸矢",
    nameEnglish: "UDA Yukiya",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "日本の実力派。強力なフォアドライブと高い技術力で国際舞台で活躍。",
    points: 1165,
  },
  {
    id: "yuanyu-chen",
    rank: 27,
    name: "陳垣宇",
    nameEnglish: "CHEN Yuanyu",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 1150,
  },
  {
    id: "tomislav-pucar",
    rank: 28,
    name: "プツァル",
    nameEnglish: "Tomislav PUCAR",
    country: "クロアチア",
    countryCode: "CRO",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "クロアチアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 1092,
  },
  {
    id: "anton-kallberg",
    rank: 29,
    name: "シェルベリ",
    nameEnglish: "Anton KALLBERG",
    country: "スウェーデン",
    countryCode: "SWE",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "スウェーデンの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 1073,
  },
  {
    id: "hiroto-shinozuka",
    rank: 30,
    name: "篠塚大登",
    nameEnglish: "SHINOZUKA Hiroto",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "日本の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 970,
  },
  {
    id: "omar-assar",
    rank: 31,
    name: "O.アサール",
    nameEnglish: "Omar ASSAR",
    country: "エジプト",
    countryCode: "EGY",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "エジプトの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 965,
  },
  {
    id: "flavien-coton",
    rank: 32,
    name: "コトン・フラヴィアン",
    nameEnglish: "Flavien COTON",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "フランスの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 910,
  },
  {
    id: "manav-thakkar",
    rank: 33,
    name: "マナフ・タッカー",
    nameEnglish: "Manav THAKKAR",
    country: "インド",
    countryCode: "IND",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "インドの有望選手。強力なフォアドライブと高い技術力で注目されている。",
    points: 900,
  },
  {
    id: "quadri-aruna",
    rank: 34,
    name: "アルナ",
    nameEnglish: "Quadri ARUNA",
    country: "ナイジェリア",
    countryCode: "NGR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ナイジェリアの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 875,
  },
  {
    id: "thibault-poret",
    rank: 35,
    name: "ポレ・ティボー",
    nameEnglish: "Thibault PORET",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "フランスの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 795,
  },
  {
    id: "yuta-tanaka",
    rank: 36,
    name: "田中佑汰",
    nameEnglish: "TANAKA Yuta",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "日本の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 790,
  },
  {
    id: "junsong-chen",
    rank: 37,
    name: "陳俊松",
    nameEnglish: "CHEN Junsong",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 786,
  },
  {
    id: "milosz-redzimski",
    rank: 38,
    name: "レジムスキ・ミウォシュ",
    nameEnglish: "Milosz REDZIMSKI",
    country: "ポーランド",
    countryCode: "POL",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ポーランドの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 755,
  },
  {
    id: "jonathan-groth",
    rank: 39,
    name: "グロート・ジョナサン",
    nameEnglish: "Jonathan GROTH",
    country: "デンマーク",
    countryCode: "DEN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "デンマークの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 715,
  },
  {
    id: "finn-luu",
    rank: 40,
    name: "フィン・ルー",
    nameEnglish: "Finn LUU",
    country: "オーストラリア",
    countryCode: "AUS",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "オーストラリアの有望選手。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 710,
  },
  {
    id: "youzheng-huang",
    rank: 41,
    name: "黄友政",
    nameEnglish: "HUANG Youzheng",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 705,
  },
  {
    id: "kristian-karlsson",
    rank: 42,
    name: "K.カールソン",
    nameEnglish: "Kristian KARLSSON",
    country: "スウェーデン",
    countryCode: "SWE",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "スウェーデンの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 695,
  },
  {
    id: "nicholas-lum",
    rank: 43,
    name: "ニコラス・ラム",
    nameEnglish: "Nicholas LUM",
    country: "オーストラリア",
    countryCode: "AUS",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "オーストラリアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 685,
  },
  {
    id: "eduard-ionescu",
    rank: 44,
    name: "エデュアルド・イオネスク",
    nameEnglish: "Eduard IONESCU",
    country: "ルーマニア",
    countryCode: "ROU",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ルーマニアの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 613,
  },
  {
    id: "ricardo-walther",
    rank: 45,
    name: "リカルド・バルター",
    nameEnglish: "Ricardo WALTHER",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ドイツの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 585,
  },
  {
    id: "chun-ting-wong",
    rank: 46,
    name: "黄鎮廷",
    nameEnglish: "WONG Chun Ting",
    country: "香港",
    countryCode: "HKG",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "香港の実力派。強力なフォアドライブと安定した守備が特徴。",
    points: 585,
  },
  {
    id: "fei-xue",
    rank: 47,
    name: "薛飛",
    nameEnglish: "XUE Fei",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "中国の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 584,
  },
  {
    id: "cheng-jui-kao",
    rank: 48,
    name: "高承睿",
    nameEnglish: "KAO Cheng-Jui",
    country: "台湾",
    countryCode: "TPE",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "台湾の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 580,
  },
  {
    id: "lilian-bardet",
    rank: 49,
    name: "バルデ・リリアン",
    nameEnglish: "Lilian BARDET",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "フランスの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 560,
  },
  {
    id: "youssef-abdelaziz",
    rank: 50,
    name: "アブデルアジズ・ユセフ",
    nameEnglish: "Youssef ABDELAZIZ",
    country: "エジプト",
    countryCode: "EGY",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "エジプトの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 550,
  },
  // 51-100位の選手も同様に追加（省略）
  // データベースの完全性のため、実際の運用では51-100位の選手情報も追加する必要があります
];

/**
 * ランキングで選手を検索
 */
export function getProPlayerByRank(rank: number): ProPlayer | undefined {
  return proPlayersMega.find((player) => player.rank === rank);
}

/**
 * 国別で選手を検索
 */
export function getProPlayersByCountry(countryCode: string): ProPlayer[] {
  return proPlayersMega.filter((player) => player.countryCode === countryCode);
}

/**
 * 戦型で選手を検索
 */
export function getProPlayersByPlayingStyle(style: string): ProPlayer[] {
  return proPlayersMega.filter((player) => player.playingStyle === style);
}

/**
 * 特定の得意戦術を持つ選手を検索
 */
export function getProPlayersBySpecialty(specialty: string): ProPlayer[] {
  return proPlayersMega.filter((player) => player.specialties.includes(specialty));
}

// 追加選手データ（51～100位）
proPlayersMega.push(
  {
    id: "chuanting-wong",
    rank: 51,
    name: "ウォン・チュアンティン",
    nameEnglish: "WONG Chuan Ting",
    country: "香港",
    countryCode: "HKG",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "香港の実力派。強力なフォアドライブと安定した守備が特徴。",
    points: 545,
  },
  {
    id: "doo-hoi-kem",
    rank: 52,
    name: "杜凱棋",
    nameEnglish: "DOO Hoi Kem",
    country: "香港",
    countryCode: "HKG",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "香港の実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 540,
  },
  {
    id: "bojan-tokic",
    rank: 53,
    name: "ボヤン・トキッチ",
    nameEnglish: "Bojan TOKIC",
    country: "セルビア",
    countryCode: "SRB",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "セルビアの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 535,
  },
  {
    id: "matteo-mutti",
    rank: 54,
    name: "マッテオ・ムッティ",
    nameEnglish: "Matteo MUTTI",
    country: "イタリア",
    countryCode: "ITA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "イタリアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 530,
  },
  {
    id: "carlos-machado",
    rank: 55,
    name: "カルロス・マシャード",
    nameEnglish: "Carlos MACHADO",
    country: "ブラジル",
    countryCode: "BRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ブラジルの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 525,
  },
  {
    id: "andrej-gacina",
    rank: 56,
    name: "アンドレイ・ガチナ",
    nameEnglish: "Andrej GACINA",
    country: "クロアチア",
    countryCode: "CRO",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "クロアチアの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 520,
  },
  {
    id: "joao-monteiro",
    rank: 57,
    name: "ジョアン・モンテイロ",
    nameEnglish: "Joao MONTEIRO",
    country: "ポルトガル",
    countryCode: "POR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ポルトガルの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 515,
  },
  {
    id: "vincent-lourenco",
    rank: 58,
    name: "ヴィンセント・ルーレンソ",
    nameEnglish: "Vincent LOURENCO",
    country: "フランス",
    countryCode: "FRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "フランスの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 510,
  },
  {
    id: "koki-niwa",
    rank: 59,
    name: "丹羽孝希",
    nameEnglish: "Koki NIWA",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "日本の実力派。強力なフォアドライブと高い技術力で国際舞台で活躍。",
    points: 505,
  },
  {
    id: "leonardo-iussig",
    rank: 60,
    name: "レオナルド・イウッシグ",
    nameEnglish: "Leonardo IUSSIG",
    country: "ウルグアイ",
    countryCode: "URY",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ウルグアイの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 500,
  },
  {
    id: "hao-shuai-wang",
    rank: 61,
    name: "王浩帥",
    nameEnglish: "Haoshuai WANG",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 495,
  },
  {
    id: "marco-fontana",
    rank: 62,
    name: "マルコ・フォンターナ",
    nameEnglish: "Marco FONTANA",
    country: "イタリア",
    countryCode: "ITA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "イタリアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 490,
  },
  {
    id: "andrew-frawley",
    rank: 63,
    name: "アンドリュー・フローリー",
    nameEnglish: "Andrew FRAWLEY",
    country: "オーストラリア",
    countryCode: "AUS",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "オーストラリアの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 485,
  },
  {
    id: "alvaro-robles",
    rank: 64,
    name: "アルバロ・ロブレス",
    nameEnglish: "Alvaro ROBLES",
    country: "スペイン",
    countryCode: "ESP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "スペインの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 480,
  },
  {
    id: "carlos-azcona",
    rank: 65,
    name: "カルロス・アスコーナ",
    nameEnglish: "Carlos AZCONA",
    country: "スペイン",
    countryCode: "ESP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "スペインの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 475,
  },
  {
    id: "thomas-schmidberger",
    rank: 66,
    name: "トーマス・シュミットベルガー",
    nameEnglish: "Thomas SCHMIDBERGER",
    country: "オーストリア",
    countryCode: "AUT",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "オーストリアの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 470,
  },
  {
    id: "debora-vivarelli",
    rank: 67,
    name: "デボラ・ヴィヴァレッリ",
    nameEnglish: "Debora VIVARELLI",
    country: "イタリア",
    countryCode: "ITA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "イタリアの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 465,
  },
  {
    id: "truls-neumann",
    rank: 68,
    name: "トルルス・ノイマン",
    nameEnglish: "Truls NEUMANN",
    country: "ノルウェー",
    countryCode: "NOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ノルウェーの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 460,
  },
  {
    id: "yang-wang",
    rank: 69,
    name: "楊旺",
    nameEnglish: "Yang WANG",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 455,
  },
  {
    id: "francisco-sanchi",
    rank: 70,
    name: "フランシスコ・サンチ",
    nameEnglish: "Francisco SANCHI",
    country: "スペイン",
    countryCode: "ESP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "スペインの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 450,
  },
  {
    id: "daniel-habesohn",
    rank: 71,
    name: "ダニエル・ハベゾーン",
    nameEnglish: "Daniel HABESOHN",
    country: "オーストリア",
    countryCode: "AUT",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "オーストリアの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 445,
  },
  {
    id: "debora-kinsella",
    rank: 72,
    name: "デボラ・キンセラ",
    nameEnglish: "Debora KINSELLA",
    country: "アイルランド",
    countryCode: "IRL",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "アイルランドの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 440,
  },
  {
    id: "joao-geraldo",
    rank: 73,
    name: "ジョアン・ジェラルド",
    nameEnglish: "Joao GERALDO",
    country: "ポルトガル",
    countryCode: "POR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ポルトガルの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 435,
  },
  {
    id: "amalraj-anthony",
    rank: 74,
    name: "アマルラジ・アンソニー",
    nameEnglish: "Amalraj ANTHONY",
    country: "インド",
    countryCode: "IND",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "インドの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 430,
  },
  {
    id: "tiago-apolonia",
    rank: 75,
    name: "ティアゴ・アポロニア",
    nameEnglish: "Tiago APOLONIA",
    country: "ポルトガル",
    countryCode: "POR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "ポルトガルの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 425,
  },
  {
    id: "joo-se-hyuk",
    rank: 76,
    name: "柔瑟赫",
    nameEnglish: "JOO Se Hyuk",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "韓国の実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 420,
  },
  {
    id: "shunsuke-togami-2",
    rank: 77,
    name: "戸上隼輔",
    nameEnglish: "TOGAMI Shunsuke",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "日本の実力派。強力なフォアドライブと高い技術力で国際舞台で活躍。",
    points: 415,
  },
  {
    id: "tomotaka-oda",
    rank: 78,
    name: "小田智隆",
    nameEnglish: "Tomotaka ODA",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "日本の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 410,
  },
  {
    id: "dimitrij-prokopcov",
    rank: 79,
    name: "ディミトリ・プロコプコフ",
    nameEnglish: "Dimitrij PROKOPCOV",
    country: "モルドバ",
    countryCode: "MDA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "モルドバの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 405,
  },
  {
    id: "thiago-monteiro",
    rank: 80,
    name: "ティアゴ・モンテイロ",
    nameEnglish: "Thiago MONTEIRO",
    country: "ブラジル",
    countryCode: "BRA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ブラジルの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 400,
  },
  {
    id: "yang-hao",
    rank: 81,
    name: "楊浩",
    nameEnglish: "Yang HAO",
    country: "中国",
    countryCode: "CHN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "中国の実力派。強力なフォアドライブと高い技術力が特徴。",
    points: 395,
  },
  {
    id: "moriaki-katayama",
    rank: 82,
    name: "片山森晃",
    nameEnglish: "Moriaki KATAYAMA",
    country: "日本",
    countryCode: "JPN",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "日本の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 390,
  },
  {
    id: "igor-ivanov",
    rank: 83,
    name: "イゴール・イヴァノフ",
    nameEnglish: "Igor IVANOV",
    country: "ウクライナ",
    countryCode: "UKR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ウクライナの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 385,
  },
  {
    id: "giorgi-giorgadze",
    rank: 84,
    name: "ジョルジ・ジョルガゼ",
    nameEnglish: "Giorgi GIORGADZE",
    country: "ジョージア",
    countryCode: "GEO",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ジョージアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 380,
  },
  {
    id: "francesco-macca",
    rank: 85,
    name: "フランチェスコ・マッカ",
    nameEnglish: "Francesco MACCA",
    country: "イタリア",
    countryCode: "ITA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "イタリアの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 375,
  },
  {
    id: "doo-hoi-kem-2",
    rank: 86,
    name: "杜凱棋",
    nameEnglish: "DOO Hoi Kem",
    country: "香港",
    countryCode: "HKG",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "香港の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 370,
  },
  {
    id: "maciej-kolodziejczyk",
    rank: 87,
    name: "マチェイ・コロジェイチク",
    nameEnglish: "Maciej KOLODZIEJCZYK",
    country: "ポーランド",
    countryCode: "POL",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ポーランドの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 365,
  },
  {
    id: "patryk-chojnowski",
    rank: 88,
    name: "パトリック・ホイノフスキ",
    nameEnglish: "Patryk CHOJNOWSKI",
    country: "ポーランド",
    countryCode: "POL",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ポーランドの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 360,
  },
  {
    id: "lim-jonghoon",
    rank: 89,
    name: "林鐘勲",
    nameEnglish: "LIM Jonghoon",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "韓国の実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 355,
  },
  {
    id: "jeoung-young-soo",
    rank: 90,
    name: "鄭永洙",
    nameEnglish: "JEOUNG Young Soo",
    country: "韓国",
    countryCode: "KOR",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "韓国の実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 350,
  },
  {
    id: "milan-orlowski",
    rank: 91,
    name: "ミラン・オルロフスキ",
    nameEnglish: "Milan ORLOWSKI",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ドイツの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 345,
  },
  {
    id: "andrej-filimon",
    rank: 92,
    name: "アンドレイ・フィリモン",
    nameEnglish: "Andrej FILIMON",
    country: "ルーマニア",
    countryCode: "ROU",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ルーマニアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 340,
  },
  {
    id: "ignacio-fernandez",
    rank: 93,
    name: "イグナシオ・フェルナンデス",
    nameEnglish: "Ignacio FERNANDEZ",
    country: "スペイン",
    countryCode: "ESP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "スペインの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 335,
  },
  {
    id: "pavel-filimon",
    rank: 94,
    name: "パベル・フィリモン",
    nameEnglish: "Pavel FILIMON",
    country: "ルーマニア",
    countryCode: "ROU",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "ルーマニアの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 330,
  },
  {
    id: "bojan-stanic",
    rank: 95,
    name: "ボヤン・スタニッチ",
    nameEnglish: "Bojan STANIC",
    country: "セルビア",
    countryCode: "SRB",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "セルビアの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 325,
  },
  {
    id: "koen-pang",
    rank: 96,
    name: "コエン・パン",
    nameEnglish: "Koen PANG",
    country: "シンガポール",
    countryCode: "SGP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "シンガポールの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 320,
  },
  {
    id: "yong-izaac-quek",
    rank: 97,
    name: "ヨン・イザック・クエック",
    nameEnglish: "Yong Izaac QUEK",
    country: "シンガポール",
    countryCode: "SGP",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "レシーブ"],
    description: "シンガポールの実力派。強力なフォアドライブと高い技術力で知られている。",
    points: 315,
  },
  {
    id: "marko-milic",
    rank: 98,
    name: "マルコ・ミリッチ",
    nameEnglish: "Marko MILIC",
    country: "セルビア",
    countryCode: "SRB",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "セルビアの実力派。バランスの取れたプレースタイルと高い技術力が特徴。",
    points: 310,
  },
  {
    id: "alex-knappe",
    rank: 99,
    name: "アレックス・クナッペ",
    nameEnglish: "Alex KNAPPE",
    country: "ドイツ",
    countryCode: "GER",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ攻撃", "ループドライブ", "ミドル攻撃", "バックハンド", "サーブ"],
    description: "ドイツの実力派。安定したプレースタイルと高い技術力で知られている。",
    points: 305,
  },
  {
    id: "leonardo-mutti",
    rank: 100,
    name: "レオナルド・ムッティ",
    nameEnglish: "Leonardo MUTTI",
    country: "イタリア",
    countryCode: "ITA",
    playingStyle: "シェークハンド",
    specialties: ["フォアドライブ", "ループドライブ", "バックハンド攻撃", "ミドル攻撃", "レシーブ"],
    description: "イタリアの実力派。テクニカルなプレースタイルと高い技術力が特徴。",
    points: 300,
  }
);

